sudo: false
language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.6

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

matrix:
  allow_failures:
    - php: nightly

before_script:
  - git clone https://github.com/Seravo/wordpress-test-template wp-tests
  - bash wp-tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION

script:
  - cd wp-tests/spec && bundle exec rspec test.rb

after_success: |
  if [ "$TRAVIS_BRANCH" == "development" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    git close development https://${DEPLOY_KEY}@github.com/dCremins/add-ons
    cd add-ons
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    git commit "$TRAVIS_COMMIT"
    git push -f -q https://${DEPLOY_KEY}@github.com/dCremins/add-ons.git development:master &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
